### ISSUE TITLE
Does not show winrate

### ISSUE THREAD

**Issue by millerk123** [dotnaonweh/solanaWallet-checker#1]
Is the gmgn API no longer showing winrate?  Do you know how I can find this?

Thanks.

**Comment by dotnaonweh** [comment]
no, gmgn API still shows the winrate, indeed sometimes the winrate does not appear

**Comment by millerk123** [comment]
Right, I see the field, but it's "None."  Do you know of any other APIs where I can find this?

**Comment by dotnaonweh** [comment]
for now I haven't found another API like gmgn sir

**Comment by millerk123** [comment]
Thank you for your help.
